# Generated by Django 3.2.8 on 2021-12-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelus',
            name='img',
            field=models.ImageField(upload_to='imgs'),
        ),
    ]
